OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL_NAME = "llama3.2:1b"

TOP_K = 5
MAX_CONTEXT_CHARS = 1800
CHUNK_SIZE_ROBOT = 400
CHUNK_SIZE_MANUAL = 700

MAX_TOKENS = 256
TEMPERATURE = 0.0

MAX_HISTORY = 6
SUMMARY_THRESHOLD = 6

SEMANTIC_THRESHOLD = 0.55

RESPONSE_CACHE_SIZE = 128

CONFIDENCE_THRESHOLD = 0.05

SESSION_EXPIRY = 1800

RATE_LIMIT_REQUESTS = 10
RATE_LIMIT_WINDOW = 60

PORT = 8000

DATA_FILE = "data/robot_data.txt"
GAME_MANUAL_FILE = "data/game_manual.pdf"
DICTIONARY_FILE = "data/dictionary.json"
PROMPTS_FILE = "data/prompts.json"
CHROMA_PATH = "data/chroma_db"
